name: Latest blog post workflow

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README with latest blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://prakash0091.hashnode.dev/"
          github_token: ${{ secrets.GITHUB_TOKEN }}
